name: Java CI with Maven multistage

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven

      - name: Step 3 - Package with Maven
        run: |
          cd my-app 
          mkdir target
          mvn -B package                              \
            -Dversion=1.0.${{ github.run_number }}    \
            -DoutputDirectory=target                  \
            --file pom.xml

      - name: Step 4 - Run app
        run: |
          cd my-app/target 
          ls -l
          java -jar my-app-1.0.${{ github.run_number }}.jar

  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Build Container image
        run: |
          docker build                                            \
            --build-arg JAR_VERSION=1.0.${{ github.run_number }}  \
            -f Dockerfile.multistage                              \
            -t ${{ secrets.DOCKER_REPO }}/my-app-multistage:1.0.${{ github.run_number }} .

      - name: Step 3 - Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Step 4 - Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}/my-app-multistage:1.0.${{ github.run_number }}

      - name: Step 5 - Run Docker image
        run: docker run ${{ secrets.DOCKER_REPO }}/my-app-multistage:1.0.${{ github.run_number }}
