name: Java CI with Maven

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven

      - name: Step 3 - Package with Maven
        run: |
          cd my-app 
          mkdir target
          mvn clean install -U
          mvn -B package                              \
            -Dversion=1.0.${{ github.run_number }}    \
            -Dpackaging=jar                           \
            -DoutputDirectory=target                  \
            --file pom.xml

      - name: Step 4 - Run app
        run: |
          cd my-app/target 
          ls -l
          java -jar my-app-1.0.${{ github.run_number }}.jar
