name: Java CI with Maven

on:
  push:
    branches: ["main"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven

      - name: Step 3 - Package with Maven
        run: |
          cd my-app 
          mkdir target
          mvn -B package                              \
            -Dversion=1.0.${{ github.run_number }}    \
            -DoutputDirectory=target                  \
            --file pom.xml

      - name: Step 4 - Run app
        run: |
          cd my-app/target 
          ls -l
          java -jar my-app-1.0.${{ github.run_number }}.jar

  publish_job:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven

      - name: Step 3 - Package with Maven (skip Tests)
        run: |
          cd my-app
          mkdir target
          mvn -B package                                \
            -DskipTests                                 \
            -Dversion=1.0.${{ github.run_number }}      \
            -DoutputDirectory=target                    \
            --file pom.xml

      - name: Step 4 - Copy artifact
        run: |
          mkdir staging
          cp my-app/target/my-app-1.0.${{ github.run_number }}.jar staging

      - name: Step 5 - Upload-artifact
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging

  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [publish_job]

    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: Package
          # path: my-app

      - name: Step 3 - Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Step 4 - Build Container image
        run: |
          pwd
          ls -l
          docker build -t ${{ secrets.DOCKER_REPO }}/my-app:1.0.${{ github.run_number }} .

      - name: Step 5 - Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}

      - name: Step 6 - Run Docker image
        run: docker run ${{ secrets.DOCKER_REPO }}/my-app:1.0.${{ github.run_number }}
